CREATE TABLE IF NOT EXISTS forecast_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_event_id BIGINT NOT NULL REFERENCES ticket_events(id),
    source_snapshot_id BIGINT NOT NULL REFERENCES snapshots(id),
    forecast_generated_at TIMESTAMPTZ NOT NULL,
    source_snapshot_captured_at TIMESTAMPTZ NOT NULL,
    hours_to_kickoff DOUBLE PRECISION,
    days_to_match DOUBLE PRECISION,
    horizon TEXT,
    model_version TEXT NOT NULL,
    historical_model TEXT,
    historical_p10 INTEGER,
    historical_p50 INTEGER,
    historical_p90 INTEGER,
    live_adjustment INTEGER NOT NULL DEFAULT 0,
    final_p10 INTEGER,
    final_p50 INTEGER,
    final_p90 INTEGER,
    forecast_status TEXT NOT NULL,
    correction_status TEXT NOT NULL,
    signal_readiness TEXT,
    live_available_total INTEGER,
    live_first_available_total INTEGER,
    live_available_index DOUBLE PRECISION,
    live_net_removed_since_first INTEGER,
    live_net_removed_since_previous INTEGER,
    live_velocity_since_previous DOUBLE PRECISION,
    live_net_removed_6h INTEGER,
    live_velocity_6h DOUBLE PRECISION,
    live_net_removed_24h INTEGER,
    live_velocity_24h DOUBLE PRECISION,
    live_acceleration_6h_vs_24h DOUBLE PRECISION,
    live_raw_snapshot_count INTEGER,
    live_clean_snapshot_count INTEGER,
    live_excluded_anomaly_count INTEGER,
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (ticket_event_id, source_snapshot_id, model_version)
);

CREATE INDEX IF NOT EXISTS idx_forecast_observations_event_generated
    ON forecast_observations(ticket_event_id, forecast_generated_at);

CREATE INDEX IF NOT EXISTS idx_forecast_observations_event_hours
    ON forecast_observations(ticket_event_id, hours_to_kickoff);

CREATE INDEX IF NOT EXISTS idx_forecast_observations_snapshot
    ON forecast_observations(source_snapshot_id);
