-- Clean bootstrap for a fresh Beyond / ticket-intelligence Supabase project.
--
-- This schema is intentionally aggregate-first: live intelligence reads
-- inventory totals from snapshots and does not need to scan sector_inventory.
-- Detailed sector inventory is still retained for audit/debugging.
-- Safe to run on a brand-new project.

BEGIN;

CREATE TABLE IF NOT EXISTS ticket_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    external_event_id TEXT NOT NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    competition TEXT,
    match_date DATE NOT NULL,
    kickoff_at TIMESTAMPTZ NOT NULL,
    source_url TEXT,
    mapping_source TEXT,
    mapping_confidence TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (provider, external_event_id)
);

CREATE INDEX IF NOT EXISTS idx_ticket_events_provider_home_kickoff
    ON ticket_events(provider, home_team, kickoff_at);

CREATE TABLE IF NOT EXISTS snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT,
    source TEXT NOT NULL,
    captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ticket_event_id BIGINT REFERENCES ticket_events(id) ON DELETE CASCADE,
    event_match_date_at_capture DATE,
    event_kickoff_at_capture TIMESTAMPTZ,
    available_total INTEGER CHECK (available_total IS NULL OR available_total >= 0),
    sector_count INTEGER CHECK (sector_count IS NULL OR sector_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_snapshots_ticket_event_captured
    ON snapshots(ticket_event_id, captured_at);

CREATE TABLE IF NOT EXISTS sector_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL REFERENCES snapshots(id) ON DELETE CASCADE,
    event_id BIGINT,
    sector TEXT NOT NULL,
    available INTEGER NOT NULL CHECK (available >= 0),
    UNIQUE (snapshot_id, sector)
);

CREATE INDEX IF NOT EXISTS idx_sector_inventory_snapshot
    ON sector_inventory(snapshot_id);

CREATE TABLE IF NOT EXISTS forecast_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_event_id BIGINT NOT NULL REFERENCES ticket_events(id) ON DELETE CASCADE,
    source_snapshot_id BIGINT NOT NULL REFERENCES snapshots(id) ON DELETE CASCADE,
    forecast_generated_at TIMESTAMPTZ NOT NULL,
    source_snapshot_captured_at TIMESTAMPTZ NOT NULL,
    hours_to_kickoff DOUBLE PRECISION,
    days_to_match DOUBLE PRECISION,
    horizon TEXT,
    model_version TEXT NOT NULL,
    historical_model TEXT,
    historical_p10 INTEGER,
    historical_p50 INTEGER,
    historical_p90 INTEGER,
    live_adjustment INTEGER NOT NULL DEFAULT 0,
    final_p10 INTEGER,
    final_p50 INTEGER,
    final_p90 INTEGER,
    forecast_status TEXT NOT NULL,
    correction_status TEXT NOT NULL,
    signal_readiness TEXT,
    live_available_total INTEGER,
    live_first_available_total INTEGER,
    live_available_index DOUBLE PRECISION,
    live_net_removed_since_first INTEGER,
    live_net_removed_since_previous INTEGER,
    live_velocity_since_previous DOUBLE PRECISION,
    live_net_removed_6h INTEGER,
    live_velocity_6h DOUBLE PRECISION,
    live_net_removed_24h INTEGER,
    live_velocity_24h DOUBLE PRECISION,
    live_acceleration_6h_vs_24h DOUBLE PRECISION,
    live_raw_snapshot_count INTEGER,
    live_clean_snapshot_count INTEGER,
    live_excluded_anomaly_count INTEGER,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (ticket_event_id, source_snapshot_id, model_version)
);

CREATE INDEX IF NOT EXISTS idx_forecast_observations_event_generated
    ON forecast_observations(ticket_event_id, forecast_generated_at);
CREATE INDEX IF NOT EXISTS idx_forecast_observations_event_hours
    ON forecast_observations(ticket_event_id, hours_to_kickoff);
CREATE INDEX IF NOT EXISTS idx_forecast_observations_snapshot
    ON forecast_observations(source_snapshot_id);

CREATE TABLE IF NOT EXISTS ticket_event_outcomes (
    ticket_event_id BIGINT PRIMARY KEY REFERENCES ticket_events(id) ON DELETE CASCADE,
    actual_attendance INTEGER NOT NULL CHECK (actual_attendance >= 0),
    attendance_definition TEXT NOT NULL DEFAULT 'official_reported_attendance',
    source_name TEXT NOT NULL,
    source_url TEXT,
    confirmed_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ticket_event_outcomes_confirmed_at
    ON ticket_event_outcomes(confirmed_at);

COMMIT;

-- Quick verification after execution:
SELECT
    to_regclass('public.ticket_events') AS ticket_events,
    to_regclass('public.snapshots') AS snapshots,
    to_regclass('public.sector_inventory') AS sector_inventory,
    to_regclass('public.forecast_observations') AS forecast_observations,
    to_regclass('public.ticket_event_outcomes') AS ticket_event_outcomes;
